name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync upstream changes
        run: |
          gh repo sync spyd3rking/dhanytv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
